# Generated by Django 5.1.4 on 2025-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscription",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Подписка на напоминания",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID телеграм"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ник в Телеграм"
            ),
        ),
    ]
