# Generated by Django 5.1.4 on 2025-01-08 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 1, 8, 12, 27, 54, 535580, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата создания привычки",
            ),
        ),
    ]
